var _a;
import { StyleOpt } from '../types/index.ds';
export var Styles = (_a = {},
    _a[StyleOpt.reset] = [0, 0],
    _a[StyleOpt.bold] = [1, 22],
    _a[StyleOpt.dim] = [2, 22],
    _a[StyleOpt.italic] = [3, 23],
    _a[StyleOpt.underline] = [4, 24],
    _a[StyleOpt.inverse] = [7, 27],
    _a[StyleOpt.hidden] = [8, 28],
    _a[StyleOpt.strikethrough] = [9, 29],
    _a[StyleOpt.black] = [30, 39],
    _a[StyleOpt.red] = [31, 39],
    _a[StyleOpt.green] = [32, 39],
    _a[StyleOpt.yellow] = [33, 39],
    _a[StyleOpt.blue] = [34, 39],
    _a[StyleOpt.magenta] = [35, 39],
    _a[StyleOpt.cyan] = [36, 39],
    _a[StyleOpt.white] = [37, 39],
    _a[StyleOpt.gray] = [90, 39],
    _a[StyleOpt.grey] = [90, 39],
    _a[StyleOpt.brightRed] = [91, 39],
    _a[StyleOpt.brightGreen] = [92, 39],
    _a[StyleOpt.brightYellow] = [93, 39],
    _a[StyleOpt.brightBlue] = [94, 39],
    _a[StyleOpt.brightMagenta] = [95, 39],
    _a[StyleOpt.brightCyan] = [96, 39],
    _a[StyleOpt.brightWhite] = [97, 39],
    _a[StyleOpt.bgBlack] = [40, 49],
    _a[StyleOpt.bgRed] = [41, 49],
    _a[StyleOpt.bgGreen] = [42, 49],
    _a[StyleOpt.bgYellow] = [43, 49],
    _a[StyleOpt.bgBlue] = [44, 49],
    _a[StyleOpt.bgMagenta] = [45, 49],
    _a[StyleOpt.bgCyan] = [46, 49],
    _a[StyleOpt.bgWhite] = [47, 49],
    _a[StyleOpt.bgGray] = [100, 49],
    _a[StyleOpt.bgGrey] = [100, 49],
    _a[StyleOpt.bgBrightRed] = [101, 49],
    _a[StyleOpt.bgBrightGreen] = [102, 49],
    _a[StyleOpt.bgBrightYellow] = [103, 49],
    _a[StyleOpt.bgBrightBlue] = [104, 49],
    _a[StyleOpt.bgBrightMagenta] = [105, 49],
    _a[StyleOpt.bgBrightCyan] = [106, 49],
    _a[StyleOpt.bgBrightWhite] = [107, 49],
    _a);
export default Styles;
//# sourceMappingURL=styles.js.map